.travis.yml, UnitTests/Program.cs
I added Travis support which successfully builds. Might be worth changing the UnitTests project to be actual UnitTests?
A build can be found here: https://travis-ci.org/JamieH/lidgren-network-gen3-1/builds/49134903
=> Travis support

Lidgren.Network/Encryption/NetAESEncryption.cs
It pass the unit tests.
This fix can have the problem described here:
[stackoverflow.com/questions/957388](http://stackoverflow.com/questions/957388/why-are-rijndaelmanaged-and-aescryptoserviceprovider-returning-different-results/4863924#4863924)
More info here: https://code.google.com/p/lidgren-network-gen3/wiki/Unity3D
=> Fix workaround for the Unity Web Player.

Lidgren.Network/NetPeer.Internal.cs, Lidgren.Network/NetUPnP.cs
The UPnP discovery process was not timing out if a discovery response was not received (e.g. if UPnP was disabled on your router). So the status would remain on "Discovering" forever and never change to "NotAvailable".
This pull request resolves this issue. Let me know if you have any questions or need anything else.
PS. I would have used the new C# 6 null-conditional operator (e.g. m_upnp?.CheckForDiscoveryTimeout()), but I wasn't sure if you were using Visual Studio 2015 yet.
=> UPnP discovery timeout

Lidgren.Network/NetBuffer.Peek.cs, Lidgren.Network/NetBuffer.Read.cs, UnitTests/ReadWriteTests.cs
Peek and Read for UInt64, with numberBits as parameter, in NetBuffer breaks when reading values above 32 bits. This is due to reading the same position twice, and not casting the second read to UInt64, breaking the bit shift.
Added tests that reproduce the bug which fails before the fix and passes after the fix.
(This is my first pull request, let me know if I did it incorrectly).
=> Fixed sublte bug in ReadUInt64(int) and PeekUInt64(int)

Lidgren.Network/NetConnectionStatistics.cs, Lidgren.Network/NetPeer.cs, Lidgren.Network/NetPeerStatistics.cs, Lidgren.Network/NetQueue.cs, Lidgren.Network/NetUPnP.cs, Lidgren.Network/NetUtility.cs
Best reviewed commit by commit, as they're pretty atomic.
There are a few issues remaining that coverity unveiled, but I didn't touch since I don't have that much expertise in the repository's code.
Specifically, `NetQueue`'s `TryDrain` and `TryDequeue` are passible to having data races caused by the `m_size` checks.
`NetPeer.Internal.cs` seems to be deadlock-able. `m_handshakes` -> `m_connections` starting on line 655 conflicts with `NetPeer.Internal.cs` line 375 and line 249 which have `m_connections` -> `m_handshakes`.
=> Different fixes caught by coverity

Lidgren.Network/NetBuffer.Read.cs
`public long ReadRangedInteger(long min, long max)` is now available for reads of LONG values.
=> Added a 64-bit version of ReadRangedInteger.

Lidgren.Network/Encryption/NetAESEncryption.cs, Lidgren.Network/NetBuffer.Write.cs, Lidgren.Network/Platform/PlatformConstrained.cs
I needed this methods to use less bandwith when sending an unknown number of objects:
WriteAt of Byte
Also there are some small changes to make Unity3d work again. I wrote in the wiki how to use this library with Unity but didn't send this changes (the tutorial, therefore, doesn't work). I forgot that the version of the library I am using is slightly different. :(
Thank you, I hope this helps!
=> WriteAt method and changes to work with Unity3D

Lidgren.Network/NetPeer.Internal.cs
If matched callback was existed near m_receiveCallbacks.count in m_receiveCallbacks, this code execute unnecessary statement. And i think that goto statement should avoid if possible.
=> Removed goto statement in NetPeer.Internal.

Lidgren.Network/NetPeer.cs
Added `bool ReadMessage(out NetIncomingMessage message)` for simplifying cases like this:
`NetIncomingMessage msg;`
`while ((msg = NetClient.ReadMessage()) != null) { }`
**into this**:
`NetIncomingMessage msg;`
`while (NetClient.ReadMessage(out msg)) { }`
=> Added `bool ReadMessage(out NetIncomingMessage message)`

Lidgren.Network/NetMessageType.cs, Lidgren.Network/NetNatIntroduction.cs, Lidgren.Network/NetPeer.Internal.cs
Clients that request an introduction now first request a confirmation from
the server to make sure unconnected messages can be sent in both
directions before attempting to make a connection. Similarly the server
automatically sends a confirmation to the client to reduce the possiblity
that either one of the endpoints has issues with sending messages to the
other.
=> Added improved NAT punch.

Lidgren.Network/NetPeer.LatencySimulation.cs
The `==` operator for IPAddress compares references not values, so `target.Address` will always not equal `ba`. Switching to `IPAddress.Equals` fixes this and allows broadcast packets to be sent on Linux.
=> Fix sending broadcast packets

Lidgren.Network/NetBuffer.Read.cs, Lidgren.Network/NetServer.cs
I was having a little issue with some kilobytes of gc because I was reading floats that where displaced (not byte aligned) in the buffer.
~~To solve it, I wrote a small Pool that only is used by the netbuffer (SimpleArrayPoolThreadSafe<T>), created an object of it on a static variable and modified the single and double read methods. Now there is not garbage from them. I did not used the pool in the string read method because the pool is too simple and may generate a lot of arrays of different size for nothing.~~
[See @Inverness comment](https://github.com/lidgren/lidgren-network-gen3/pull/70#issuecomment-228561416)
~~The method to read strings still generates garbage~~
Readstring will generate garbage only if it doesn't fit on the saved buffer
The removed unnecessary array …
=> Less GC when reading floats and doubles thanks to a pool of byte[] + Removed a unnecessary array creation and destruction

Lidgren.Network.MultiTarget.sln, Lidgren.Network.MultiTarget/Lidgren.Network.MultiTarget.csproj, UnitTests.Core/UnitTests.Core.csproj, UnitTests.MultiTarget/App.config, UnitTests.MultiTarget/Properties/AssemblyInfo.cs, UnitTests.MultiTarget/UnitTests.MultiTarget.csproj
These SLN/csproj files will compile lidgren to multi-target .NET 4.0/.NET 4.6/.NET 4.6.1/.NET 4.6.2/.NET Standard 2.0, so it can run in .NET Core. Unit tests have also been ported and run in both .NET 4.6 (original but pointing to the multi-target build) and .NET Core 2.0
=> additive-only multi-targeting support (.net 4.0 -> .net core 2.0)

Lidgren.Network/NetUPnP.cs
Slightly modified the port forwarding requests for separate ports when two machines on the same network need the same ports to be forwarded.
I also renamed the property on the delete forwarding function to match the name of the same port on the add forwarding function so that it was clear which port was required. 
Could potentially have the internal port fallback to the Port property of the NetPeer object but I thought this was safer.
Also looks like tabs vs spaces are fighting. Sorry about that.
=> Allow different internal and external ports on port forwarding

Lidgren.Network/NetServer.cs
The only SendToAll method that accepted a sequence channel was the override that allows you to skip a NetConnection (which you could pass null to get the same result as this change - but this skips the performance cost of doing that).
=> Fixed NetServer missing SendToAll override with sequence channel parameter

Lidgren.Network/NetUnreliableSenderChannel.cs
The Enqueue method was able to queue only 2 messages before sending, all other messages were dropped.
=> Fix enqueuing unreliable packets with disabled flow control

Lidgren.Network/NetPeer.Internal.cs, Lidgren.Network/NetPeer.LatencySimulation.cs, Lidgren.Network/NetPeer.cs, Lidgren.Network/NetPeerConfiguration.cs, Lidgren.Network/NetUtility.cs
This pull request fixes a couple of bugs introduced in https://github.com/lidgren/lidgren-network-gen3/pull/123:
- null ref exception when we try to use host name instead of actual IP
- wrong target IP address when we are not using IPv6 dual mode
=> Fixed bugs after introducing IPv6 dual mode

Lidgren.Network/NetPeer.Internal.cs
The issue report is here https://github.com/lidgren/lidgren-network-gen3/issues/132#
`NetPeer.Heartbeat()` method will no longer prematurely return in case of encountering an incorrect packet.
Alas, Github showing a incredibly large diff. The actual changes are as minimal as possible:
1. the inner body of the loop `do { ... } while (m_socket.Available > 0);`  extracted into a new private method (`ReceiveSocketData`).
2. the try-catch block around `m_socket.ReceiveFrom(...)` call moved outside the `do { ... } while (m_socket.Available > 0);`  loop.
This way any socket exceptions will break the loop and properly handled (as expected).
Meanwhile the `return;` calls from the inner loop are no longer return from the whole `Heartbeat()` method as they will only return from the method …
=> Fixed an issue #132

Lidgren.Network/NetPeer.Internal.cs, Lidgren.Network/NetPeer.cs, Lidgren.Network/NetPeerConfiguration.cs, Lidgren.Network/NetUtility.cs
This PR fixes the IPv6 support *properly*. The two previous PRs, #123 and #126, both made a mess out of it:
PR #123 implemented IPv6 by breaking non-dualstack IPv4 support.
PR #126 fixed IPv4 support by breaking non-dualstack IPv6 support.
This change fixes the mess entirely. IPv4, IPv6 and IPv6-dual-stack are now all independently supported and work as expected.
Namely IPv4 can't receive IPv6, IPv6 can only receive IPv4 if NetPeerConfiguration.DualStack is set. You can still have an IPv6-only socket.
I'll leave some review comments on the PR for less-immediately obvious changes.
cc @CallumDev @Badartefact
=> IPv6: Space Wizard Edition.

Lidgren.Network.MultiTarget/Lidgren.Network.MultiTarget.csproj
1. Added a reference to Microsoft.NETFramework.ReferenceAssemblies so that the project can be built hassle-free on .NET Core.
2. Use the AssemblyInfo.cs from the existing code and disable automatic AssemblyInfo generation (to avoid clash).
3. Dropped target for net40. The regular Framework project file didn't support it either and it doesn't build due to a missing API (MapToIPv6).
=> Improve multi-target csproj.
